ENGLISH_TO_NORWEGIAN = {
    "Mexico": "Mexico",
    "South Africa": "Sør-Afrika",
    "South Korea": "Sør-Korea",
    "Korea Republic": "Sør-Korea",
    "Czech Republic": "Tsjekkia",
    "Czechia": "Tsjekkia",
    "Canada": "Canada",
    "Bosnia and Herzegovina": "Bosnia-Hercegovina",
    "Bosnia & Herzegovina": "Bosnia-Hercegovina",
    "Bosnia-Herzegovina": "Bosnia-Hercegovina",
    "United States": "USA",
    "United States of America": "USA",
    "Paraguay": "Paraguay",
    "Haiti": "Haiti",
    "Scotland": "Skottland",
    "Australia": "Australia",
    "Turkey": "Tyrkia",
    "Türkiye": "Tyrkia",
    "Brazil": "Brasil",
    "Morocco": "Marokko",
    "Qatar": "Qatar",
    "Switzerland": "Sveits",
    "Ivory Coast": "Elfenbenskysten",
    "Côte d'Ivoire": "Elfenbenskysten",
    "Cote d'Ivoire": "Elfenbenskysten",
    "Ecuador": "Ecuador",
    "Germany": "Tyskland",
    "Curaçao": "Cura\u00e7ao",
    "Curacao": "Cura\u00e7ao",
    "Netherlands": "Nederland",
    "Japan": "Japan",
    "Sweden": "Sverige",
    "Tunisia": "Tunisia",
    "Saudi Arabia": "Saudi-Arabia",
    "Uruguay": "Uruguay",
    "Spain": "Spania",
    "Cape Verde": "Kapp Verde",
    "Cape Verde Islands": "Kapp Verde",
    "Iran": "Iran",
    "New Zealand": "New Zealand",
    "Belgium": "Belgia",
    "France": "Frankrike",
    "Senegal": "Senegal",
    "Iraq": "Irak",
    "Norway": "Norge",
    "Argentina": "Argentina",
    "Algeria": "Algerie",
    "Austria": "Østerrike",
    "Ghana": "Ghana",
    "Panama": "Panama",
    "England": "England",
    "Croatia": "Kroatia",
    "Portugal": "Portugal",
    "DR Congo": "DR Kongo",
    "Congo DR": "DR Kongo",
    "Democratic Republic of Congo": "DR Kongo",
    "Democratic Republic of the Congo": "DR Kongo",
    "Uzbekistan": "Usbekistan",
    "Colombia": "Colombia",
    "Jordan": "Jordan",
}